export const matches = [
    {
      unique_id: 1214574,
      date: "2020-08-16T00:00:00.000Z",
      dateTimeGMT: "2020-08-16T04:30:00.000Z",
      team_1: "Sri Lanka",
      team_2: "Australia lion",
      team_1_Players: "asb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdx",
      team_2_Players: "yuisb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdx",
      type: "ODI",
      toss_winner_team: "Sri Lanka",
      squad: false,
      venue: "England",
      winner_team: "Australia lion",
      matchStarted: true
    },
    {
      unique_id: 1214575,
      date: "2020-08-16T00:00:00.000Z",
      dateTimeGMT: "2020-08-16T04:30:00.000Z",
      team_1: "India Cricket",
      team_2: "Pakistan Club",
      team_1_Players: "bmsb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdp",
      team_2_Players: "qweusb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdbv",
      type: "ODI",
      venue: "London",
      toss_winner_team: "India Cricket",
      winner_team: "India Cricket",
      squad: false,
      matchStarted: true
    },
    {
      unique_id: 1228927,
      date: "2020-08-16T00:00:00.000Z",
      dateTimeGMT: "2020-08-16T10:00:00.000Z",
      team_1: "England Boss",
      team_2: "Newzleand",
      venue: "Melborne",
      team_1_Players: "asb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdx",
      team_2_Players: "yuisb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdx",
      toss_winner_team: "England Boss",
      winner_team: "Newzleand",
      squad: false,
      matchStarted: true,
      type: ""
    },
    {
      unique_id: 1229054,
      date: "2020-08-16T00:00:00.000Z",
      dateTimeGMT: "2020-08-16T04:30:00.000Z",
      team_1: "India Club",
      team_2: "West Indies",
      venue: "Sri lanka",
      team_1_Players: "bmsb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdp",
      team_2_Players: "qweusb, asodn, ffrf, frwr, wewr, asd, asd, reeegf, ewsfvdbv",
      squad: true,
      toss_winner_team: "West Indies",
      winner_team: "India Club",
      matchStarted: true,
      type: ""
    }
]