export const TableData =[
    {
        id:1,
        team: "India",
        won : "12",
        lost: "2",
        runrate: "14.2",
        drawn: "0",
        Pts: "16",
    },
    {
        id:2,
        team: "Pakistan",
        won : "4",
        lost: "6",
        runrate: ".2",
        drawn: "0",
        Pts: "8",
    },
    {
        id:3,
        team: "West Indies",
        won : "9",
        lost: "6",
        runrate: "6.2",
        drawn: "0",
        Pts: "6",
    },
    {
        id:4,
        team: "Australia",
        won : "14",
        lost: "1",
        runrate: "19.2",
        drawn: "0",
        Pts: "19",
    },
    {
        id:6,
        team: "Newzland",
        won : "10",
        lost: "3",
        runrate: "14.2",
        drawn: "0",
        Pts: "12",
    },
    {
        id:6,
        team: "Sri Lanka",
        won : "11",
        lost: "5",
        runrate: "11.2",
        drawn: "0",
        Pts: "10",
    },
    {
        id:7,
        team: "Africa",
        won : "11",
        lost: "6",
        runrate: "2.2",
        drawn: "0",
        Pts: "14",
    },
    {
        id:8,
        team: "England",
        won : "14",
        lost: "7",
        runrate: "11.2",
        drawn: "0",
        Pts: "9",
    },
]